[package]
name = "examples"
version = "0.0.0"
edition = "2021"
authors = ["Nikolai Vazquez"]
license = "MIT OR Apache-2.0"
description = "Examples for Divan, a statistically-comfy benchmarking library."
readme = "../README.md"
publish = false

[dev-dependencies]
divan = { workspace = true }

[[bench]]
name = "math"
harness = false
