[package]
name = "examples"
version = "0.0.0"
edition = "2021"
authors = ["Nikolai Vazquez"]
license = "MIT OR Apache-2.0"
description = "Examples for Divan, a statistically-comfy benchmarking library."
readme = "../README.md"
publish = false

[dev-dependencies]
divan = { workspace = true }
fastrand = "2"
image = "0.24"
rayon = "1"

[[bench]]
name = "collections"
harness = false

[[bench]]
name = "image"
harness = false

[[bench]]
name = "math"
harness = false

[[bench]]
name = "panic"
harness = false

[[bench]]
name = "sort"
harness = false

[[bench]]
name = "string"
harness = false

[[bench]]
name = "time"
harness = false
